; Скопировать в /etc/php/8.3/fpm/conf.d/99-messenger-uploads.ini и перезапустить php8.3-fpm
upload_max_filesize = 2048M
post_max_size = 2056M
max_file_uploads = 100
max_execution_time = 600
max_input_time = 600
memory_limit = 512M
